################################################################
# Basic configuration of PP Bridge App
################################################################
# The name of the bridge app, it will shown in the ProtoPie Connect as message source.
name: Bridge App from config file
# The ProtoPie Connect host address
host: http://localhost
# The ProtoPie Connect port
port: 9981