################################################################
# Basic configuration of PP Bridge App
################################################################
bridge:
  # The name of the bridge app, it will shown in the ProtoPie Connect as message source.
  name: Bridge App 
  # The ProtoPie Connect host address
  host: http://localhost
  # The ProtoPie Connect port
  port: 9981

################################################################
# Logging configuration
################################################################
logging:
  # Global logging level, any log message has level lower than this will not be logged.
  # Default is `DEBUG`, you should leave this alone in most cases.
  level: DEBUG
  # console logging handler, this controls logging content in the terminal.
  console:
    # logging level for console handler, default is `INFO`, you can change to `WARNING` if you want to see less detail.
    level: INFO
    # logging message format for console handler, see `logging` documentation for more information.
    format: "> %(asctime)s [%(levelname)s]:\n\t%(message)s"
  # file logging handler, this controls logging content in the log file.
  file:
    # logging level for file handler, default is `DEBUG`.
    level: DEBUG
    # log file path and name.
    name: piedmont.log
    # format for file hanlder, see `logging` documentation for more information.
    format: "%(asctime)s [%(name)s][%(levelname)s]:\t%(message)s"

################################################################
# Serial configuration
################################################################
serial:
  # The separator of serial message. It will divide the message into message name and data;
  # for example:
  #
  #   KNOB_GEAR_SHIFT::N
  # 
  # This is a message received from serial, `KNOB_GEAR_SHIFT` will be the name of the message.
  # `N` will be the data of the message, it will be send to the message handler function.
  separator: "::"
  # Serial port to your board.
  # Change this to your own port before start the plugin.
  port: /dev/cu.usbmodem144201
  baudrate: 115200
  timeout: 1

################################################################
# Options configuration, optional
################################################################
options: